theme                  : jekyll-theme-minimal
url                    : "https://Unfinishedgod.github.io"


# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-145407326-3"
    anonymize_ip         : # true, false (default)

theme: jekyll-theme-architect